First pyspark ETL job code

diff --git a/.github/workflows/run-etl.yml b/.github/workflows/run-etl.yml
--- a/.github/workflows/run-etl.yml
+++ b/.github/workflows/run-etl.yml
@@ -16,24 +16,29 @@ jobs:
       with:
         ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}
 
-    - name: List files in repo
-      run: ls -R
-
-    - name: Copy ETL folder to EC2
-      run: |
-        # Ensure destination folder exists
-        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} \
-          "mkdir -p ~/pyspark-etl-project/"
-
-        # Copy the ETL folder recursively
-        scp -o StrictHostKeyChecking=no -r pyspark-etl-project/etl ubuntu@${{ secrets.EC2_PUBLIC_IP }}:~/pyspark-etl-project/
-
-    - name: Install Python dependencies on EC2
+    - name: Copy ETL project to EC2
       run: |
         ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} \
-        "sudo apt update && sudo apt install -y python3-pip openjdk-11-jdk && pip3 install -r ~/pyspark-etl-project/etl/requirements.txt"
+          "mkdir -p ~/pyspark-etl-project"
+
+        scp -o StrictHostKeyChecking=no -r pyspark-etl-project/etl \
+          ubuntu@${{ secrets.EC2_PUBLIC_IP }}:~/pyspark-etl-project/
+
+    - name: Install Python dependencies (if needed)
+      run: |
+        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} \
+        "pip3 install --user -r ~/pyspark-etl-project/etl/requirements.txt"
 
     - name: Run PySpark ETL on EC2
       run: |
-        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} \
-        "~/pyspark-etl-project/etl/submit.sh"
+        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
+          set -e   # stop if any command fails
+
+          cd ~/pyspark-etl-project/etl
+
+          spark-submit \
+            --packages org.apache.hadoop:hadoop-aws:3.3.2,mysql:mysql-connector-java:8.0.33 \
+            etl.py
+
+          echo "ETL JOB COMPLETED SUCCESSFULLY"
+        EOF
